# Generated by Django 5.2.1 on 2025-05-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('pnombre', models.CharField(max_length=50)),
                ('snombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apaterno', models.CharField(max_length=50)),
                ('amaterno', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
            ],
        ),
    ]
