# Generated by Django 5.2.1 on 2025-05-21 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FerremasHome', '0002_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
